TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += devKeithley_2700.proto

#=======================================
include $(TOP)/configure/RULES
